### PR TITLE
Port CoffeeScript to ES6

### PR DESCRIPTION
**Pull request by devongovett**
I started this project over 3 years ago now, as a part of [PDFKit](https://github.com/devongovett/pdfkit) which was written in CoffeeScript. At the time, CoffeeScript provided a nice syntax on top of JavaScript, especially with it's class syntax and other features. It served my projects well, but it's time to move on. CoffeeScript hasn't received major updates in quite some time now, and won't be getting a lot of the nice features in ES6. ES6 borrowed many of it's features from CoffeeScript, so why not just move to ES6?

There are several reasons to move, but the biggest for me is encouraging outside contribution. Simply, more people know and are willing to contribute to projects written in JavaScript than CoffeeScript. Also, as I mentioned before, ES6 has many of CoffeeScript's good parts, infused with some other cool stuff. I've been working on other projects with it, and really enjoy it.

I used [decaffinate](https://github.com/decaffeinate/decaffeinate) to do the initial port, and then cleaned up the result by hand. Decaffinate isn't perfect, but it was a HUGE help in doing this, so thanks to @eventualbuddha for that project.

Still working on cleaning up some stuff, but tests are passing which is a good sign.

### CODE REVIEW

**Comment by bramstein** [comment]
How much work is left for this to be merged in? Anything I can help out with?

**Comment by jwerre** [comment]
I'm also happy to help with this.

**Comment by devongovett** [comment]
I mostly want to review all of the converted files and clean up any formatting things left behind by decaffinate. Sorry I've been slow on this, super busy lately. Will get on it soon.

**Comment by jahewson** [comment]
Hi Devon, I have a few thoughts on some small structural changes to the upcoming ES6 code so that it plays nice with webpack. Also I have some TypeScript annotations if you're interested.

**Comment by devongovett** [comment]
@jahewson feel free to share your thoughts about webpack. Have a link to the typescript annotations?

**Comment by Pomax** [comment]
As is the constant case in JS, new bundlers keep popping up - if this is still in the "trying to make it work" stages, it might be worth having a quick look to see if [rollup](https://github.com/rollup/rollup) gets the job done.

**Comment by eventualbuddha** [comment]
As one of the maintainers of rollup and creator of decaffeinate, I support that 😉

**Comment by jahewson** [comment]
I've now published my TypeScript definitions to [jahewson/fontkit-types](https://github.com/jahewson/fontkit-types/blob/master/typings/fontkit/fontkit.d.ts).

As far as webpack goes, one hurdle has been that the dependency on `fs` isn't needed in the browser but results in webpack pulling in the sizeable `brfs` dependency.

Another issue is that the different modules which make up fontkit have interdependencies which cause the entirety of fontkit to be bundled, no matter how few features are used. For example, I don't need subsetting but because each Font exposes a `createSubset` function, and imports the relevant `XXXSubset` module, webpack things that I need that module too. One solution to this would be to construct a Subset from a Font, rather than having a Font construct a Subset.

Likewise because I don't need to save files, I don't need the encoding parts of restructure, which get pulled in by webpack too.

Probably the biggest issue is that I can't ship support for only certain font formats, I don't need DFont, WOFF, or WOFF2, but because they all get registered, they all get bundled. I think the registering API really needs to be made explicit.

Overall, adding a bit more `import` boilerplate would really make things more modular.

**Comment by devongovett** [comment]
You can `require('fontkit/base')` to load it without any font formats enabled, then manually register the formats you want with e.g.`fontkit.registerFormat(require('fontkit/src/TTFFont'));`.

As for other stuff, rollup might be able to help here with its tree shaking features...

**Comment by jahewson** [comment]
I use a mix of ES5 and ES6 code, so Rollup isn't an option for me. I have everything working with webpack - it's just that the config is a pile of hacks. Requiring `fontkit/base` is cool though, that's exactly what I had in mind.

**Comment by devongovett** [comment]
Merged! Published to npm in v1.4.0.

Updated the build process a bit. Now using Babel 6, and Rollup before publishing to npm. Still including the ES6 source in the package though, for custom builds.

**Comment by Teoxoy** [comment]
@jahewson are the typescript definitions still available somewhere?

**Pull request merged**
