### PR TITLE
adds tests for font.layout 'fi'

### PR DESCRIPTION
**Pull request by lecstor**
Should the two tests pass? Currently only the first one does.
Seems to be an issue with the OTLayoutEngine.substitute method, but that's as deep as I got.

### CODE REVIEW

**Comment by lecstor** [comment]
a few other random tests seem to indicate that this *only* occurs for `fi`. None of the other letter combos I tried did the same thing.

**Comment by Pomax** [comment]
quite a lot of console.log in there... forgot to remove for the pr?

**Comment by lecstor** [comment]
8) not forgot, was intended to be more of a bug report than a real "please merge" PR.

**Comment by lecstor** [comment]
but happy to clean it up if you do want to merge it in.

**Comment by devongovett** [comment]
I believe this is working as intended by the font designer. "fi" returns a ligature glyph that represents both characters in one glyph.

**Comment by lecstor** [comment]
hmm.. maybe I'm using this incorrectly then, but I found the issue because I had the word "simplified" in my text and it displayed as "simpli  ed". This was using NotoSans-Regular.
Thanks, I'll have another look at my stuff.

**Comment by lecstor** [comment]
ok, I don't think it's me.
If you change the para font in the PDFKit docs to OpenSans-Regular, generate the PDF guide, then copy the text `source file and create` from the first paragraph and paste it elsewhere you'll get `source  le and create`

**Comment by Pomax** [comment]
Oh, that's an issue with how copying from PDF works.

Without [`ActualText`](https://blog.idrsolutions.com/2012/04/understanding-the-pdf-file-format-actualtext/) instructions in the PDF, text that contains ligatures or is stored with a subset font embed (which does not guarantee glyph id preservation) typically means you won't be pasting what you think you copied. In cases like these, the PDF needs to explicitly contain additional code that says "this sequence is actually the string ..." so that when you copy a text-selection, the PDF engine actually does a text substitution so that you actually get the text you "expect" (or the creator reasonably expects you to want to see).

In this case it's quite likely that the PDF internally uses a glyph id for the `fl` ligature that resolves for the embedded font, but is *not* the same glyph id as is used by whatever font you're using in the application you're pasting into, so you're going to get either a `.notdef` glyph, or you might even get the wrong glyph entirely because that id exists but points to something completely different.

**Comment by lecstor** [comment]
Well I don't think it's an issue with the font in SublimeText, it correctly displays copypasta from a PDF using NotoSans to display a wide range of characters (testing Greek, Russian, etc).

Using `glyphsForString` has solved my issue.

I have also just noticed that the same thing happens for `ff`.

```
  1) character to glyph mapping layout bug should return the right glyfs for "ff":

      AssertionError: [ 909 ] deepEqual [ 73, 73 ]
      + expected - actual

       [
      -  909
      +  73
      +  73
       ]
```

copypasta direct from PDF:
```
Getting Started with PDFKit Installation
Installation uses the npm package manager. Just type the following command after installing npm. npm install pdfkit
Creating a document
Creating a PDFKit document is quite simple. Just require the pdfkit module in your Co eeScript or JavaScript source  le and create an instance of the PDFDocument class.
PDFDocument = require 'pdfkit'
doc = new PDFDocument
PDFDocument instances are readable Node streams. They don't get saved anywhere automatically, but you can call the pipe method to send the output of the PDF document to another writable Node stream as it is being written. When you're done with your document, call the end method to  nalize it. Here is an example showing how to pipe to a  le or an HTTP response.
doc.pipe fs.createWriteStream('/path/to/file.pdf') # write to PDF
doc.pipe res                                       # HTTP response
# add stuff to PDF here using methods described below...
# finalize the PDF and end the stream
doc.end()
```

**Pull request closed without merging**
