### PR TITLE
Allow setting text direction

### PR DESCRIPTION
**Pull request by khaledhosny**

### CODE REVIEW

**Comment by khaledhosny** [comment]
This should fix #105, but my JS is rather rusty and I’m also not sure all my changes are correct. The test failure is caused by #106.

**Comment by devongovett** [comment]
#106 was caused by language not being passed to ShapingPlan: https://github.com/devongovett/fontkit/pull/107/files#diff-d621a286065887d944719db18cdb1749L107. I've updated it to call `selectScript` in `OTLayoutEngine#setup` instead.

Secondarily, the language tags have to be four character strings, e.g. `'URD '`, but the test only passed `'URD'`. Perhaps we should pad the string to 4 characters so users don't need to know that...

**Comment by devongovett** [comment]
That should already happen: see [here](https://github.com/devongovett/fontkit/blob/master/src/opentype/shapers/DefaultShaper.js#L8-L11) and [here](https://github.com/devongovett/fontkit/blob/master/src/opentype/shapers/DefaultShaper.js#L30).

**Comment by khaledhosny** [comment]
My comment was about commit 56856fb8cdeb08732435404cd621449093f0c8b8 and whether `getAvailableFeatures()` needs the direction or not.

**Comment by devongovett** [comment]
Oh I see. That code is just to get the full list of available features in the font, not which ones are applied.

**Comment by khaledhosny** [comment]
Oh, all good then 😄

**Pull request merged**
