### PR TITLE
Make fontkit cross-platform compatible again

### LINKED ISSUE #118: Remove Makefile in favour of npm scripts
There is a `Makefile` right now that prevents running fontkit on Windows, but the only commands in it are simple one-liner scripts that can be trivially relocated to the `package.json` instead as npm script calls.

In the interest of cross-platform compatibility, it is totally worth removing that Makefile.

### PR DESCRIPTION
**Pull request by Pomax**
Closes #118 

This makes everything node-runnable again, obviating the need for OS-presupplied utilities. It adds `npm-run-all` as a script running convenience, and it adds `shx` as cross-platform utility runner for common unix utils such as `cp` and `rm`. Finally, it also adds `cross-env` to ensure that environment variables are set in a way that work in unix, linux, OSX, and Windows alike.

`npm test` shows all tests passing, with the same coverage.

### CODE REVIEW

**Comment by Pomax** [comment]
@devongovett probably worth landing since CI says it's all good =)

**Comment by devongovett** [comment]
Not sure how I feel about this. Doesn't Windows have bash now? What about cygwin?

Admittedly my knowledge of windows is very limited, but Make is a tool that's designed exactly for this purpose. npm scripts are not.

**Comment by Pomax** [comment]
Linux Subsystem is still in beta, so don't rely on it. Cygwin is massively huge, also not a very dev-friendly thing to rely on when Node already *has* all the tools needed for proper cross-platform work. There is literally no reason to have any kind of reliance on `make` and `Makefile` if you're writing a node project.

These change do the exact same thing as before, they just do it in a proper node way now.

**Comment by davelab6** [comment]
(I agree with Mike :)

**Comment by Pomax** [comment]
hm. bump?

**Comment by Pomax** [comment]
bump, again? =)

**Comment by Pomax** [comment]
rerebump =)

**Comment by Pomax** [comment]
@devongovett this is still very much worth landing, if you no longer really work on fontkit could I selfishly ask you just hit merge so that people who do still use it a lot in the font work can use this normally on windows, without affecting anyone on *n*x operating systems?

**Comment by davelab6** [comment]
Thank you Devon!!

**Comment by devongovett** [comment]
Yeah sorry guys, I've been busy with other projects lately. Today I made an org https://github.com/foliojs and I'll be moving fontkit, textkit, pdfkit, and all related dependencies across the whole stack there so more contributors can be involved with reviewing and merging code. @diegomura of react-pdf is already helping out a bit, and I hope to bring others on as maintainers as well. Hopefully that will help with the long term support for these projects.

**Comment by Pomax** [comment]
That's great to hear!

**Pull request merged**
