### PR TITLE
improved performance for the KernProcessor

### PR DESCRIPTION
**Pull request by anthonmanix**
This addresses the pdfkit issue [#615](https://github.com/devongovett/pdfkit/issues/615)

### CODE REVIEW

**Comment by Pomax** [comment]
Can you show the timing differences for this vs. 0.8 vs 0.7? Based on the changes to the code, this looks incredibly unlikely to restore the kind of performance loss the linked issue was about.

**Comment by anthonmanix** [comment]
```javascript
console.time('build');

const fs = require('fs');
const PDFDoc = require('pdfkit');

let doc = new PDFDoc();
let stream = fs.createWriteStream('out.pdf');
doc.pipe(stream);

doc.font('fonts/OpenSans-Regular.ttf');
for (let i = 0; i < 10; i += 1) {
  doc.text('Lorem ipsum dolor sit amet, ei per tritani evertitur intellegebat, ad aperiam volumus inimicus ius, harum offendit referrentur an vix. His meis quodsi corpora eu. No mei nostro possim bonorum, vis veniam albucius praesent te, mel error appetere consequuntur eu. Ea latine deleniti efficiendi sea, ut his vocent discere omnesque, zril graeci abhorreant te per. Eius tamquam inciderint vim ex. Mei minimum consequat at, ius eu dicta clita tollit.');
  doc.moveDown();
}

doc.end();
stream.on('close', function () {
  console.timeEnd('build');
  process.exit(0);
});
```

pdfkit 0.7.1: ~100ms
pdfkit 0.8.0: ~8000ms
pdfkit 0.8.0 (with fix): ~1000ms

**Comment by Pomax** [comment]
You can probably microoptimize a bit more because array lengths are invariant, so should not be looked up in the loop itself. Instead of a `for (let i=0; i<array.length; i+=1)`, pull the invariant out: `for (let i=0, end=array.length; i<end; i+=1)`. Or, if you absolutely need the most speed out of your loop, don't run up, run down: `for(let i=array.length-1; i>-1; i--)` when the code allows for it.

**Comment by devongovett** [comment]
I'm very surprised that babel is causing this much of a performance hit. Did you run the profiler?

**Comment by anthonmanix** [comment]
Not sure how to read these...

[prof.zip](https://github.com/devongovett/fontkit/files/778568/prof.zip)

**Comment by anthonmanix** [comment]
More improvement by implementing binary search.

Previous example is now ~500ms

**Comment by vijender1256** [comment]
@devongovett @anthonmanix are there any plans to release new version after the fixes ?, I am having huge performace issues while downloading pdf with more than 100 pages.. Thanks

**Comment by vijender1256** [comment]
@devongovett @anthonmanix Sorry to ask this one more time, but when are we expecting for the fixed version to be released. Thanks

**Comment by anthonmanix** [comment]
unfortunately this is out of my control

in the meantime i was checking the babel configuration and also got some performance improvements if i set the loose flag to true (about 8x). similar as modifying the loops. so it seems that the main bottleneck is the kern processor. other loops don't effect the performance as much.

**Comment by Pomax** [comment]
Does setting that flag yield the same level of improvement as manual optimization? If so, that is an infinitely better optimization to have in this PR than code changes to the ES6+ source.

**Comment by anthonmanix** [comment]
yes... within the margin of error. but the binary search still helps further.

should i revert changes and keep binary search?

**Comment by devongovett** [comment]
binary search is the right solution here. can you try the existing binary search helper function and see how it compares? https://github.com/devongovett/fontkit/blob/master/src/utils.js#L1

**Comment by Pomax** [comment]
Oh, yeah the binary search rewrite is absolutely valuable to keep, I was talking about the plain syntax rewrite (the change from `for/of` to `for(let;condition;step)`, which shouldn't need a rewrite in the source, babel should be told to just do that properly).

**Comment by anthonmanix** [comment]
i set the loose flag, reverted the loop changes and implemented the binary search from utils

**Comment by Harbs** [comment]
I would think that creating a hashtable of kerning values (using a string composed of the glyph ids) would be the most efficient way to get kern values. Even a binary search will have many more iterations than a simple hashtable lookup. It would require only a single loop to construct the hashtable.

**Comment by liborm85** [comment]
@devongovett  When will new version with performance fix?

**Comment by devongovett** [comment]
Thanks and sorry for the delay. Released in v1.5.3.

**Pull request merged**
