### PR TITLE
 Pad language string with space if < 4 characters

### PR DESCRIPTION
**Pull request by khaledhosny**

### CODE REVIEW

**Comment by khaledhosny** [comment]
Should we upper case the string as well?

**Comment by Pomax** [comment]
does the spec say languages must be uppercase? If not, probably not a good idea to force it.

**Comment by devongovett** [comment]
They look like they're all uppercase in the spec: https://www.microsoft.com/typography/otspec/languagetags.htm

**Comment by khaledhosny** [comment]
I think it is safe to convert language tags to upper since all defined ones are uppercase. HarfBuzz does the same.

**Comment by moyogo** [comment]
I think there was a proposal to use lowercase language system tags for ISO 693 languages that are not supported by the OT language system tags but I didn’t go anywhere.

Currently, it’s probably fine to uppercase them.

**Comment by khaledhosny** [comment]
OK, I guess better leave things as they are now.

**Pull request merged**
